# Torch
### Notes and code based on youtube videos by user Patrick Loeber: https://www.youtube.com/playlist?list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4

In [1]:
import torch
import numpy as np

### Tensor Operations

In [2]:
x = torch.randint(20, size=(2,2))
y = torch.randint(6, size=(2,2))

print('x = ', x, 'y = ', y)

x =  tensor([[ 0,  0],
        [10, 17]]) y =  tensor([[1, 4],
        [4, 0]])


Element-wise operations written as $\textit{x+y, x-y, x*y, x/y}$ or $\textit{x.add(y)}$. Add a trailing underscore to do the operation in place. 

In [3]:
print(x + y)
y.add_(x)
print(y)
if y.all() == (x+y).all():
    print("Same thing.")

tensor([[ 1,  4],
        [14, 17]])
tensor([[ 1,  4],
        [14, 17]])
Same thing.


Can use .item() to extract (scalar) tensor component as long as the tensor is sliced properly.

In [4]:
z = torch.randint(10, (2, 2))
print(z)
scalar = z[0, 1]
print(scalar, scalar.item())
print(type(scalar), type(scalar.item()))

tensor([[4, 1],
        [0, 4]])
tensor(1) 1
<class 'torch.Tensor'> <class 'int'>


$\textit{t.view()}$ can be used to reshape a tensor. Reshape dimensions must have the same product as previous dimension product ie $m \times n$ maps to $a \times b$ where $mn = ab$.

In [5]:
a = torch.rand(4, 4)
print(a)
b = a.view(-1, 2) #reshape -1 makes automatic choice of other dimension when given one dimension as
#next input
print(b)

tensor([[0.2115, 0.9093, 0.9184, 0.9050],
        [0.2088, 0.7229, 0.1240, 0.6312],
        [0.7044, 0.6910, 0.4384, 0.0906],
        [0.1265, 0.3170, 0.5314, 0.5708]])
tensor([[0.2115, 0.9093],
        [0.9184, 0.9050],
        [0.2088, 0.7229],
        [0.1240, 0.6312],
        [0.7044, 0.6910],
        [0.4384, 0.0906],
        [0.1265, 0.3170],
        [0.5314, 0.5708]])


Can turn a numpy array into a torch tensor and vice versa. Care needs to be taken though as the tensor and array both occupy the same memory location if only working with the CPU (not GPU) so changes to one are also changes to the other.

In [6]:
o = torch.ones(5)
print(o)
p = o.numpy() 
print(type(p)) 

s = np.ones(5)
print(s)
t = torch.from_numpy(s)
print(type(t))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>


### Autograd

When initialising a tensor, setting the $\textit{requires\_grad}$ equal to True let's torch know that you will want to take the gradient of this tensor later on. This attribute needs to be specified before back propagation.

In [22]:
x = torch.tensor([0.0,1.0,2.0], requires_grad=True) 
print(x)

y = x + 2
print(y)

tensor([0., 1., 2.], requires_grad=True)
tensor([2., 3., 4.], grad_fn=<AddBackward0>)


Since requires_grad is True, torch tracks the operations made in the grad_fn attribute of the tensors and creates a computation graph for back propagation later. The forward pass calculates the output $y = f(x)$ and since gradient is specified, torch automatically creates a function for us which is used in back propagation to calculate the gradient. $y$ has attribute grad_fn which points to gradient function dy/dx.

In [26]:
print(x)
print(y)
z = y*y*2
print(z)
v = torch.tensor([1.0, 1.0, 2.0], dtype = torch.float32)
z.backward(v)
print(x.grad)

tensor([0., 1., 2.], requires_grad=True)
tensor([2., 3., 4.], grad_fn=<AddBackward0>)
tensor([ 8., 18., 32.], grad_fn=<MulBackward0>)
tensor([24.8000, 48.0000, 96.0160])


$\textit{z.backward()}$ calculates the derivative of z wrt the first tensor in the branch chain ie calculates dz/dx. However, $\textit{z.backward()}$, doesn't work by itself unless the output is a scalar- it throws the error "grad can be implicitly created only for scalar outputs". For it to work you need to perform the vector jacobian product or similar higher dimensional product with the correct rank tensor to output the gradient. The vector jacobian product is similar to a change of basis matrix transformation. This is done by writing $\textit{z.backward(v)}$ where $v$ is the correct rank tensor required for a properly defined product. Not sure about how the components of v are picked from a neural networks perspective but in the usual jacobian product it usually contains the primary basis coordinates ~.

The $\textit{.grad}$ part outputs a tensor of same rank as the input ($x$ here) containing the "vector" in the vector jacobian product, usually the pre-computated gradients wrt each output.

Actions can be taken to allow a tensor to be created without being added to the branch diagram. This prevents torch from tracking history and calculating the grad_fn attribute allowing for adjustment of the neural network. Can be done in three ways:

In [9]:
t = torch.randn(3, requires_grad=True)
print(t)

t.requires_grad_(False) #trailing underscore modifies in place
print(t)
t.requires_grad_(True)

o = t.detach()
print(t)
print(o) 

with torch.no_grad():
    y = t + 2
    print(y)

tensor([ 0.6850, -0.8555, -0.5232], requires_grad=True)
tensor([ 0.6850, -0.8555, -0.5232])
tensor([ 0.6850, -0.8555, -0.5232], requires_grad=True)
tensor([ 0.6850, -0.8555, -0.5232])
tensor([2.6850, 1.1445, 1.4768])


Whenever we call the backwards function is called, all gradients up to that point in that chain are included and summed. Need to be careful to make sure correct tensors included in calculation.

### Simple Example NN

Gradients important for minimising the loss function by calculating $\frac{\partial}{\partial x} Loss$. The three steps of a neural network are:
- Forward pass: Apply functions and calculate loss
- Compute partial derivatives at each node on branch diagram wrt each input parameter
- Backward pass: Compute derivative of the loss function wrt each input parameter using the chain rule on the derivatives from the previous step

Loss is difference between predicted output and the actual output squared. Output is modelled as linear combination of the weights, $\textbf{w}$ and some input, $\textbf{x}$, ie $\hat{y} = \textbf{w} \cdot \textbf{x}$, this makes loss equal to $\left( \hat{y} - y \right)^2 = \left(\textbf{w} \cdot \textbf{x} - y \right)^2$. Minimise our loss by calculating the derivative of the loss wrt our weights in the vector $\textbf{w}$.

In [10]:
#Practice Example
x=1
y=2
w=1
#from pen and paper calculation, (wx - y)^2 = 1 and dLoss/dw = 2s(1) = 2(-1)(1) = -2 where s = wx - y

x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True) #interested in gradient

#forward pass and compute loss
y_hat = w*x
loss = (y_hat - y)**2
print(loss)

#backward pass
loss.backward() #gradient computation
print(w.grad)
#works correctly

#Next steps: update weights
#            do next forward and backward pass
#            repeat

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


### More Concrete Example

Next we make a more concrete model by manually implementing prediction, gradient computation, loss computation and parameter updates with a view to moving to automation using torch's in-built features. This should provide a solid background understanding of how neural networks work.

In [11]:
#Linear regression: f = w*x and ignore bias at the moment

#Function to approximate: f = 2*x

#Training sample
X = np.array([1, 2, 3, 4, 5], dtype=np.float32)
Y = np.array([2, 4, 6, 8, 10], dtype=np.float32)

#Initialise weight. Start with 0.0
w = 0.0

#Manual calculation
#Model prediction
def forward(x):
    return w*x

#Loss
def loss(y, y_predicted): #y_predicted is the model output ie what is calculated in the forward pass
    return ((y_predicted - y)**2).mean() #mean squared error

#Gradient
#mean squared error = 1/N*(w*x - y)**2
#dJ/dw = 1/N*dJ/du*du/dw = 1/N*2u*x = 1/N*2x*(w*x - y)
def gradient(x, y, y_predicted):
    return np.dot(2*x, y_predicted-y).mean() #scalar product

print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    #prediction = forward pass
    y_pred = forward(X)

    #loss
    l = loss(Y, y_pred)

    #gradients
    dw = gradient(X, Y, y_pred)

    #update weights
    w -= learning_rate*dw #gradient descent algorithm

    if epoch % 1 == 0: #print every step
        print(f'epoch {epoch + 1}: w = {w:.3f}, loss = {l:.8f}')
print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 2.200, loss = 44.00000000
epoch 2: w = 1.980, loss = 0.44000015
epoch 3: w = 2.002, loss = 0.00440001
epoch 4: w = 2.000, loss = 0.00004400
epoch 5: w = 2.000, loss = 0.00000044
epoch 6: w = 2.000, loss = 0.00000000
epoch 7: w = 2.000, loss = 0.00000000
epoch 8: w = 2.000, loss = 0.00000000
epoch 9: w = 2.000, loss = 0.00000000
epoch 10: w = 2.000, loss = 0.00000000
epoch 11: w = 2.000, loss = 0.00000000
epoch 12: w = 2.000, loss = 0.00000000
epoch 13: w = 2.000, loss = 0.00000000
epoch 14: w = 2.000, loss = 0.00000000
epoch 15: w = 2.000, loss = 0.00000000
epoch 16: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 18: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
epoch 20: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


So the key steps are:
- Create your input and idealised output arrays (X and Y above).
- Initialise the weights
- Define forward pass, loss calculation and gradient functions
- Pick a learning rate and number of iterations (small learning rate good for fine tuning of weights but can require larger number of iterations)
- Create a training loop which repeatedly calls the forward pass, loss and gradient functions 
- Update the weights in some way so that they eventually minimise the loss function
- Once loss is minimised to zero your function is fully approximated

### Automate Gradient Calculation

Above everything is calculated manually. Now to automate using torch, starting with the gradient calculation.


In [30]:
#Linear regression: f = w*x and ignore bias at the moment

#Function to approximate: f = 2*x

#Training sample
X = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10], dtype=torch.float32) #now tensors

#Initialise weight. Start with 0.0
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True) #w also a tensor and we're interested
#in the gradient of the loss wrt w we specify that requires_grad=True

#Manual calculation
#Model prediction
def forward(x):
    return w*x

#Loss
def loss(y, y_predicted): #y_predicted is the model output ie what is calculated in the forward pass
    return ((y_predicted - y)**2).mean() #mean squared error

print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    #prediction = forward pass
    y_pred = forward(X)

    #loss
    l = loss(Y, y_pred)

    #gradients = backward pass
    l.backward() #dl/dw calculated completely by torch now

    #update weights
    #Require this to not be included in the gradient branch diagram otherwise the back pass will
    #include this step in the calculation of gradient and mess with the network so this becomes...
    with torch.no_grad():
        w -= learning_rate*w.grad #gradient descent algorithm

    #zero gradients. When we call l.backward() it writes gradients and puts them in w.grad() attribute
    w.grad.zero_()

    if epoch % 10 == 0: #print every step
        print(f'epoch {epoch + 1}: w = {w:.3f}, loss = {l:.8f}')
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.440, loss = 44.00000000
epoch 11: w = 1.870, loss = 0.30573449
epoch 21: w = 1.989, loss = 0.00212438
epoch 31: w = 1.999, loss = 0.00001476
epoch 41: w = 2.000, loss = 0.00000010
epoch 51: w = 2.000, loss = 0.00000000
epoch 61: w = 2.000, loss = 0.00000000
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


Back propagation not as accurate as the analytical gradient calculation so more iterations required when using torch for back propagation. This seems like an issue for simple networks but comes in handy for more complicated networks where a lot more gradients are needed to be calculated at each node so torch is better than analytical gradient calculation for large networks with many nodes.

Adding more data to your inputs and idealised outputs improves convergence time of network.

### Automate Loss and Parameter Updates

General training pipeline:

- Design model (number of inputs and outputs and forward pass with different operations and layers)
- Construct loss and optimiser
- Training loop:
  - Forward pass: Compute prediction
  - Backward pass: Compute gradients
  - Update weights
  - Iterate loop a couple times

In [13]:
import torch.nn as nn 

#Copy paste from above
#Linear regression: f = w*x and ignore bias at the moment

#Function to approximate: f = 2*x

#Training sample
X = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10], dtype=torch.float32) #now tensors

#Initialise weight. Start with 0.0
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True) #w also a tensor and we're interested
#in the gradient of the loss wrt w we specify that requires_grad=True

#Manual calculation
#Model prediction
def forward(x):
    return w*x

#Loss automation

print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss() #same loss function as before 
optimiser = torch.optim.SGD([w], lr=learning_rate) #SGD- Stochastic Gradient Descent. torch.optim.SGD requires parameters 
#to optimise

for epoch in range(n_iters):
    #prediction = forward pass
    y_pred = forward(X)

    #loss
    #This part of the training loop can remain the same as above we have loss = nn.MSELoss() which is 
    #a callable function
    l = loss(Y, y_pred)

    #gradients = backward pass
    l.backward() #dl/dw calculated completely by torch now

    #update weights. optimiser does this automatically
    optimiser.step()

    #zero gradients again for optimiser
    optimiser.zero_grad()

    if epoch % 10 == 0: #print every step
        print(f'epoch {epoch + 1}: w = {w:.3f}, loss = {l:.8f}')
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.440, loss = 44.00000000
epoch 11: w = 1.870, loss = 0.30573449
epoch 21: w = 1.989, loss = 0.00212438
epoch 31: w = 1.999, loss = 0.00001476
epoch 41: w = 2.000, loss = 0.00000010
epoch 51: w = 2.000, loss = 0.00000000
epoch 61: w = 2.000, loss = 0.00000000
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


Above the calculation of the loss and optimisation of weights are handled automatically by torch.nn.optim.SGD algorithm. Now to automate the prediction model (forward pass).

### Automate Forward Pass

Using torch $\textit{nn.Linear}$ we can implement a simple linear transformation to the incoming data.

In [14]:
#Copy paste from above
#Linear regression: f = w*x and ignore bias at the moment

#Function to approximate: f = 2*x

#Training sample
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32) #tensors need to be reshaped for nn.Linear
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32) #
#After reshaping
n_samples, n_features = X.shape
print(n_samples, n_features) #returns 4 1 which means there are 4 samples each with one feature
#number of rows in input X needs to match the number of samples

input_size = n_features
output_size = n_features #Give these to model

X_test = torch.tensor([5], dtype=torch.float32) #test tensor

#Explicit weights and forward pass no longer required as the torch model knows the form we want from its
#input parameters:
model = nn.Linear(input_size, output_size)
#Normally have to design the forward pass ourselves but linear regression is trivial so is provided by 
#torch off the bat

#Loss automation

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}') 
#model input must be a tensor so create test tensor. Use .item for print statement as model output should
#be a scalar

#Training
learning_rate = 0.01
n_iters = 1000

loss = nn.MSELoss() #same loss function as before 
#optimiser also needs modified as we no longer have weights. Change to model.parameters()
optimiser = torch.optim.SGD(model.parameters(), lr=learning_rate) #SGD- Stochastic Gradient Descent. torch.optim.SGD 
#requires parameters to optimise

for epoch in range(n_iters):
    #prediction = forward pass
    y_pred = model(X) #updated prediction using model instead of forward function from before

    #loss
    #This part of the training loop can remain the same as above we have loss = nn.MSELoss() which is 
    #a callable function
    l = loss(Y, y_pred)

    #gradients = backward pass
    l.backward() #dl/dw calculated completely by torch now

    #update weights. optimiser does this automatically
    optimiser.step()

    #zero gradients again for optimiser
    optimiser.zero_grad()

    if epoch % 50 == 0: #print every step
        [w, b] = model.parameters() #creates a list of lists of lists
        print(f'epoch {epoch + 1}: w = {w[0][0].item():.3f}, loss = {l:.8f}')
print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

#AT FIRST PASS THIS DOESN'T WORK TOO WELL. NEED A LOT MORE ITERATIONS

4 1
Prediction before training: f(5) = 3.648
epoch 1: w = 0.823, loss = 11.04624844
epoch 51: w = 1.764, loss = 0.08088276
epoch 101: w = 1.797, loss = 0.05992890
epoch 151: w = 1.825, loss = 0.04440355
epoch 201: w = 1.849, loss = 0.03290017
epoch 251: w = 1.870, loss = 0.02437696
epoch 301: w = 1.888, loss = 0.01806181
epoch 351: w = 1.904, loss = 0.01338263
epoch 401: w = 1.917, loss = 0.00991568
epoch 451: w = 1.929, loss = 0.00734691
epoch 501: w = 1.939, loss = 0.00544360
epoch 551: w = 1.947, loss = 0.00403336
epoch 601: w = 1.955, loss = 0.00298846
epoch 651: w = 1.961, loss = 0.00221426
epoch 701: w = 1.966, loss = 0.00164063
epoch 751: w = 1.971, loss = 0.00121560
epoch 801: w = 1.975, loss = 0.00090069
epoch 851: w = 1.979, loss = 0.00066735
epoch 901: w = 1.982, loss = 0.00049447
epoch 951: w = 1.984, loss = 0.00036637
Prediction after training: f(5) = 9.972


In [35]:
model.weight

model(torch.tensor([5], dtype=torch.float32))

tensor([9.9718], grad_fn=<ViewBackward0>)